### PR TITLE
Prevent VigemBusNotFoundException and add missing app.config file required for compile

### PR DESCRIPTION
**Pull request by TheNathannator**
Prevent the ViGEmBusNotFoundException by preventing WiitarThing from starting if ViGEmBus is not installed.

app.config taken from MWisBest's repo: https://github.com/MWisBest/WiitarThing/blob/master/WiitarThing/app.config
Couldn't compile the project due to this file being missing.

old description:
```
taken from MWisBest's repo: https://github.com/MWisBest/WiitarThing/blob/master/WiitarThing/app.config

Was trying to make a check for if ViGEmBus was installed to prevent the `Nefarius.ViGEm.Client.Exceptions.VigemBusNotFoundException` error caused by not having it installed, but couldn't compile the project to view the windows due to this file being missing.
```

### CODE REVIEW

**Comment by Aida-Enna** [comment]
I'm trying to check this out, but it looks like github is having issues right now. I'll check back on it later today, thank you!

**Comment by TheNathannator** [comment]
Yeah I noticed, been trying to make a comment for a bit: I managed to figure out that ViGEmBus check and I pushed it to my branch. I think it's supposed to show that commit here, but I don't see it yet? just a heads-up lol

**Comment by TheNathannator** [comment]
Still don't see the new commit, wondering if I might just have to wait for you to merge this first lol

**Comment by TheNathannator** [comment]
I'm gonna try just changing a random meaningless thing and pushing that to get the commit to show up

**Comment by TheNathannator** [comment]
Nice, that worked

**Comment by TheNathannator** [comment]
Info is edited, I don't have any other plans to add on atm, so feel free to merge this whenever you're ready.

**Comment by Aida-Enna** [comment]
Sorry, got swamped with IRL stuff. Merging in now and will release a new build. Thank you!

**Comment by TheNathannator** [comment]
You're welcome!

**Pull request merged**
